### ISSUE TITLE
Quarto - execute options

### ISSUE THREAD

**Issue by bensoltoff** [cis-ds/course-site#383]
What options for `execute` in the YAML are generic to all Quarto rendering vs. specific to `knitr`? Looks like I can cache and change echo using

```yaml
---
execute:
  echo: false
  cache: true
---
```

[Read the documentation more](https://quarto.org/docs/computations/execution-options.html) and adjust Quarto slides to match.
